# Generated by Django 5.1.3 on 2025-02-08 08:06

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_useruniquetoken'),
    ]

    operations = [
        migrations.AddField(
            model_name='useruniquetoken',
            name='datetime',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
