# Generated by Django 5.1.3 on 2025-02-08 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_useruniquetoken_datetime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useruniquetoken',
            name='datetime',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
