# Generated by Django 5.1.3 on 2025-06-02 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_emailverificationtoken'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='price',
            field=models.IntegerField(default=0, verbose_name='Бюджет (руб.)'),
        ),
    ]
